### PR TITLE
Bamboeleverancier

### PR DESCRIPTION
**Pull request by websseo**

### CODE REVIEW

**Comment by CiotkaCierpienia** [comment]
Please stop adding PR with your keys in the code

**Comment by websseo** [comment]
Yeah I know thanks for your comment! still getting the hang of the whole
GitHub workflow, I wasn't meant to merge my branch into your master repo!

Op do 1 jun. 2023 15:39 schreef Kinga ***@***.***>:

**Comment by websseo** [comment]
Thank you for taking time to reply, i will do that:) By the way, the deploy
to netlify button on the github repo page of your template isn't working,
did you know that?


Op do 1 jun 2023 om 19:01 schreef Kinga ***@***.***>:

**Comment by CiotkaCierpienia** [comment]
I did not; we will check that. Can you report the issue? We would appreciate that.

**Pull request closed without merging**
